const MISSIONS = [
  // --- KHÍ & ĐƠN CHẤT ---
  // --- LITI (Li) ---
  {
    id: "li2o",
    name: "Liti Oxit",
    formula: "Li₂O",
    desc: "Dùng trong men gốm sứ.",
    recipe: { Li: 2, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "lioh",
    name: "Liti Hiđroxit",
    formula: "LiOH",
    desc: "Hấp thụ CO2 trong tàu vũ trụ.",
    recipe: { Li: 1, O: 1, H: 1 },
    type: "Hợp chất",
  },
  {
    id: "licl",
    name: "Liti Clorua",
    formula: "LiCl",
    desc: "Hợp chất tạo màu đỏ trong pháo hoa.",
    recipe: { Li: 1, Cl: 1 },
    type: "Hợp chất",
  },
  {
    id: "libr",
    name: "Liti Bromua",
    formula: "LiBr",
    desc: "Chất hút ẩm cực mạnh.",
    recipe: { Li: 1, Br: 1 },
    type: "Hợp chất",
  },
  {
    id: "lii",
    name: "Liti Iotua",
    formula: "LiI",
    desc: "Dùng trong pin chịu nhiệt.",
    recipe: { Li: 1, I: 1 },
    type: "Hợp chất",
  },
  {
    id: "lino3",
    name: "Liti Nitrat",
    formula: "LiNO₃",
    desc: "Chất oxy hóa màu đỏ.",
    recipe: { Li: 1, N: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "li2so4",
    name: "Liti Sunfat",
    formula: "Li₂SO₄",
    desc: "Dùng điều trị rối loạn lưỡng cực.",
    recipe: { Li: 2, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "li2co3",
    name: "Liti Cacbonat",
    formula: "Li₂CO₃",
    desc: "Nguyên liệu sản xuất pin Li-hợp chất.",
    recipe: { Li: 2, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "li3po4",
    name: "Liti Photphat",
    formula: "Li₃PO₄",
    desc: "Chất dẫn điện hợp chất rắn.",
    recipe: { Li: 3, P: 1, O: 4 },
    type: "Hợp chất",
  },

  // --- NATRI (Na) ---
  {
    id: "na2o",
    name: "Natri Oxit",
    formula: "Na₂O",
    desc: "Thành phần của thủy tinh.",
    recipe: { Na: 2, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "naf",
    name: "Natri Florua",
    formula: "NaF",
    desc: "Chất chống sâu răng.",
    recipe: { Na: 1, F: 1 },
    type: "Hợp chất",
  },
  {
    id: "nabr",
    name: "Natri Bromua",
    formula: "NaBr",
    desc: "Thuốc an thần nhẹ.",
    recipe: { Na: 1, Br: 1 },
    type: "Hợp chất",
  },
  {
    id: "nai",
    name: "Natri Iotua",
    formula: "NaI",
    desc: "Bổ sung Iốt, trị bướu cổ.",
    recipe: { Na: 1, I: 1 },
    type: "Hợp chất",
  },
  {
    id: "nano3",
    name: "Natri Nitrat",
    formula: "NaNO₃",
    desc: "Diêm tiêu Chile, làm phân bón.",
    recipe: { Na: 1, N: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "nano2",
    name: "Natri Nitrit",
    formula: "NaNO₂",
    desc: "Chất bảo quản thịt.",
    recipe: { Na: 1, N: 1, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "na2so3",
    name: "Natri Sunfit",
    formula: "Na₂SO₃",
    desc: "Chất tẩy trắng giấy.",
    recipe: { Na: 2, S: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "nahso4",
    name: "Natri Bisunfat",
    formula: "NaHSO₄",
    desc: "Chất làm sạch bể bơi.",
    recipe: { Na: 1, H: 1, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "nahso3",
    name: "Natri Bisunfit",
    formula: "NaHSO₃",
    desc: "Phụ gia thực phẩm E222.",
    recipe: { Na: 1, H: 1, S: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "na2s",
    name: "Natri Sunfua",
    formula: "Na₂S",
    desc: "Dùng trong công nghiệp giấy.",
    recipe: { Na: 2, S: 1 },
    type: "Hợp chất",
  },
  {
    id: "na3po4",
    name: "Natri Photphat",
    formula: "Na₃PO₄",
    desc: "Chất tẩy rửa dầu mỡ.",
    recipe: { Na: 3, P: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "nach3coo",
    name: "Natri Axetat",
    formula: "CH₃COONa",
    desc: "Đá nóng (tạo nhiệt khi kết tinh).",
    recipe: { C: 2, H: 3, O: 2, Na: 1 },
    type: "Hợp chất",
  },

  // --- KALI (K) ---
  {
    id: "k2o",
    name: "Kali Oxit",
    formula: "K₂O",
    desc: "Dùng trong phân bón và xà phòng.",
    recipe: { K: 2, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "kf",
    name: "Kali Florua",
    formula: "KF",
    desc: "Ứng dụng khắc thủy tinh.",
    recipe: { K: 1, F: 1 },
    type: "Hợp chất",
  },
  {
    id: "kbr",
    name: "Kali Bromua",
    formula: "KBr",
    desc: "Thuốc chống co giật cũ.",
    recipe: { K: 1, Br: 1 },
    type: "Hợp chất",
  },
  {
    id: "ki",
    name: "Kali Iotua",
    formula: "KI",
    desc: "Thuốc bảo vệ tuyến giáp.",
    recipe: { K: 1, I: 1 },
    type: "Hợp chất",
  },
  {
    id: "k2so4",
    name: "Kali Sunfat",
    formula: "K₂SO₄",
    desc: "Phân bón kali không chứa clo.",
    recipe: { K: 2, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "k2co3",
    name: "Kali Cacbonat",
    formula: "K₂CO₃",
    desc: "Thành phần tro bếp.",
    recipe: { K: 2, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "khco3",
    name: "Kali Bicacbonat",
    formula: "KHCO₃",
    desc: "Chất chữa cháy dạng bột.",
    recipe: { K: 1, H: 1, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "k3po4",
    name: "Kali Photphat",
    formula: "K₃PO₄",
    desc: "Phụ gia thực phẩm.",
    recipe: { K: 3, P: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "k2s",
    name: "Kali Sunfua",
    formula: "K₂S",
    desc: "Tạo hiệu ứng pháo hoa.",
    recipe: { K: 2, S: 1 },
    type: "Hợp chất",
  },
  {
    id: "k2cro4",
    name: "Kali Cromat",
    formula: "K₂CrO₄",
    desc: "Chất chỉ thị màu vàng.",
    recipe: { K: 2, Cr: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "k2cr2o7",
    name: "Kali Dicromat",
    formula: "K₂Cr₂O₇",
    desc: "Chất oxi hóa mạnh màu cam.",
    recipe: { K: 2, Cr: 2, O: 7 },
    type: "Hợp chất",
  },

  // --- RUBIDI (Rb) & XESI (Cs) ---
  {
    id: "rbcl",
    name: "Rubidi Clorua",
    formula: "RbCl",
    desc: "Dùng trong hóa sinh.",
    recipe: { Rb: 1, Cl: 1 },
    type: "Hợp chất",
  },
  {
    id: "cscl",
    name: "Xesi Clorua",
    formula: "CsCl",
    desc: "Dùng tách DNA.",
    recipe: { Cs: 1, Cl: 1 },
    type: "Hợp chất",
  },

  // --- BERYLI (Be) ---
  {
    id: "beo",
    name: "Beryli Oxit",
    formula: "BeO",
    desc: "Gốm dẫn nhiệt cao.",
    recipe: { Be: 1, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "becl2",
    name: "Beryli Clorua",
    formula: "BeCl₂",
    desc: "Xúc tác Friedel-Crafts.",
    recipe: { Be: 1, Cl: 2 },
    type: "Hợp chất",
  },

  // --- MAGIÊ (Mg) ---
  {
    id: "mgoh2",
    name: "Magiê Hiđroxit",
    formula: "Mg(OH)₂",
    desc: "Thuốc sữa chữa đau dạ dày.",
    recipe: { Mg: 1, O: 2, H: 2 },
    type: "Hợp chất",
  },
  {
    id: "mgcl2",
    name: "Magiê Clorua",
    formula: "MgCl₂",
    desc: "Đông tụ đậu phụ (nigari).",
    recipe: { Mg: 1, Cl: 2 },
    type: "Hợp chất",
  },
  {
    id: "mgbr2",
    name: "Magiê Bromua",
    formula: "MgBr₂",
    desc: "Thuốc an thần nhẹ.",
    recipe: { Mg: 1, Br: 2 },
    type: "Hợp chất",
  },
  {
    id: "mgi2",
    name: "Magiê Iotua",
    formula: "MgI₂",
    desc: "Hóa chất phòng thí nghiệm.",
    recipe: { Mg: 1, I: 2 },
    type: "Hợp chất",
  },
  {
    id: "mgso4",
    name: "Magiê Sunfat",
    formula: "MgSO₄",
    desc: "Muối Epsom, giảm đau cơ.",
    recipe: { Mg: 1, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "mgco3",
    name: "Magiê Cacbonat",
    formula: "MgCO₃",
    desc: "Bột phấn cho vận động viên.",
    recipe: { Mg: 1, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "mgno32",
    name: "Magiê Nitrat",
    formula: "Mg(NO₃)₂",
    desc: "Phân bón dễ tan.",
    recipe: { Mg: 1, N: 2, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "mg3po42",
    name: "Magiê Photphat",
    formula: "Mg₃(PO₄)₂",
    desc: "Thành phần trong xương.",
    recipe: { Mg: 3, P: 2, O: 8 },
    type: "Hợp chất",
  },
  {
    id: "mgs",
    name: "Magiê Sunfua",
    formula: "MgS",
    desc: "Vật liệu bán dẫn.",
    recipe: { Mg: 1, S: 1 },
    type: "Hợp chất",
  },

  // --- CANXI (Ca) ---
  {
    id: "cao",
    name: "Canxi Oxit",
    formula: "CaO",
    desc: "Vôi sống, hút ẩm mạnh.",
    recipe: { Ca: 1, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "cacl2",
    name: "Canxi Clorua",
    formula: "CaCl₂",
    desc: "Chất làm tan băng tuyết.",
    recipe: { Ca: 1, Cl: 2 },
    type: "Hợp chất",
  },
  {
    id: "caf2",
    name: "Canxi Florua",
    formula: "CaF₂",
    desc: "Quặng Fluorit, làm thấu kính.",
    recipe: { Ca: 1, F: 2 },
    type: "Hợp chất",
  },
  {
    id: "cabr2",
    name: "Canxi Bromua",
    formula: "CaBr₂",
    desc: "Dung dịch khoan dầu khí.",
    recipe: { Ca: 1, Br: 2 },
    type: "Hợp chất",
  },
  {
    id: "cai2",
    name: "Canxi Iotua",
    formula: "CaI₂",
    desc: "Hóa chất nhiếp ảnh.",
    recipe: { Ca: 1, I: 2 },
    type: "Hợp chất",
  },
  {
    id: "caso4",
    name: "Canxi Sunfat",
    formula: "CaSO₄",
    desc: "Thạch cao khan.",
    recipe: { Ca: 1, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "cano32",
    name: "Canxi Nitrat",
    formula: "Ca(NO₃)₂",
    desc: "Phân bón Canxi.",
    recipe: { Ca: 1, N: 2, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "ca3po42",
    name: "Canxi Photphat",
    formula: "Ca₃(PO₄)₂",
    desc: "Thành phần chính của xương và răng.",
    recipe: { Ca: 3, P: 2, O: 8 },
    type: "Hợp chất",
  },
  {
    id: "cas",
    name: "Canxi Sunfua",
    formula: "CaS",
    desc: "Bột lân quang.",
    recipe: { Ca: 1, S: 1 },
    type: "Hợp chất",
  },
  {
    id: "cahpo4",
    name: "Canxi Hiđrophotphat",
    formula: "CaHPO₄",
    desc: "Bổ sung canxi thức ăn chăn nuôi.",
    recipe: { Ca: 1, H: 1, P: 1, O: 4 },
    type: "Hợp chất",
  },

  // --- BARI (Ba) ---
  {
    id: "bao",
    name: "Bari Oxit",
    formula: "BaO",
    desc: "Hút ẩm cho ống catốt.",
    recipe: { Ba: 1, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "bano32",
    name: "Bari Nitrat",
    formula: "Ba(NO₃)₂",
    desc: "Pháo hoa màu xanh lá cây.",
    recipe: { Ba: 1, N: 2, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "baso4",
    name: "Bari Sunfat",
    formula: "BaSO₄",
    desc: "Chất cản quang chụp X-quang dạ dày.",
    recipe: { Ba: 1, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "baco3",
    name: "Bari Cacbonat",
    formula: "BaCO₃",
    desc: "Thuốc diệt chuột (độc).",
    recipe: { Ba: 1, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "bas",
    name: "Bari Sunfua",
    formula: "BaS",
    desc: "Tạo màu xám trắng.",
    recipe: { Ba: 1, S: 1 },
    type: "Hợp chất",
  },

  // --- NHÔM (Al) ---
  {
    id: "alcl3",
    name: "Nhôm Clorua",
    formula: "AlCl₃",
    desc: "Chất chống mồ hôi.",
    recipe: { Al: 1, Cl: 3 },
    type: "Hợp chất",
  },
  {
    id: "albr3",
    name: "Nhôm Bromua",
    formula: "AlBr₃",
    desc: "Xúc tác phản ứng hóa học.",
    recipe: { Al: 1, Br: 3 },
    type: "Hợp chất",
  },
  {
    id: "ali3",
    name: "Nhôm Iotua",
    formula: "AlI₃",
    desc: "Phản ứng mạnh với nước.",
    recipe: { Al: 1, I: 3 },
    type: "Hợp chất",
  },
  {
    id: "al2so43",
    name: "Nhôm Sunfat",
    formula: "Al₂(SO₄)₃",
    desc: "Phèn nhôm, làm trong nước.",
    recipe: { Al: 2, S: 3, O: 12 },
    type: "Hợp chất",
  },
  {
    id: "alno33",
    name: "Nhôm Nitrat",
    formula: "Al(NO₃)₃",
    desc: "Chất thuộc da, chống ăn mòn.",
    recipe: { Al: 1, N: 3, O: 9 },
    type: "Hợp chất",
  },
  {
    id: "alpo4",
    name: "Nhôm Photphat",
    formula: "AlPO₄",
    desc: "Chất kết dính chịu nhiệt.",
    recipe: { Al: 1, P: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "al4c3",
    name: "Nhôm Cacbua",
    formula: "Al₄C₃",
    desc: "Phản ứng với nước tạo khí Metan.",
    recipe: { Al: 4, C: 3 },
    type: "Hợp chất",
  },
  {
    id: "al2s3",
    name: "Nhôm Sunfua",
    formula: "Al₂S₃",
    desc: "Tạo mùi H2S khi gặp nước.",
    recipe: { Al: 2, S: 3 },
    type: "Hợp chất",
  },
  {
    id: "alf3",
    name: "Nhôm Florua",
    formula: "AlF₃",
    desc: "Thành phần điện phân nhôm.",
    recipe: { Al: 1, F: 3 },
    type: "Hợp chất",
  },

  // --- KẼM (Zn) ---
  {
    id: "znso4",
    name: "Kẽm Sunfat",
    formula: "ZnSO₄",
    desc: "Bổ sung kẽm, thuốc nhỏ mắt.",
    recipe: { Zn: 1, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "znno32",
    name: "Kẽm Nitrat",
    formula: "Zn(NO₃)₂",
    desc: "Xúc tác hóa học.",
    recipe: { Zn: 1, N: 2, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "znco3",
    name: "Kẽm Cacbonat",
    formula: "ZnCO₃",
    desc: "Calamine trị ngứa da.",
    recipe: { Zn: 1, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "znbr2",
    name: "Kẽm Bromua",
    formula: "ZnBr₂",
    desc: "Chắn bức xạ hạt nhân.",
    recipe: { Zn: 1, Br: 2 },
    type: "Hợp chất",
  },
  {
    id: "zni2",
    name: "Kẽm Iotua",
    formula: "ZnI₂",
    desc: "Chất cản quang X-quang.",
    recipe: { Zn: 1, I: 2 },
    type: "Hợp chất",
  },
  {
    id: "znoh2",
    name: "Kẽm Hiđroxit",
    formula: "Zn(OH)₂",
    desc: "Chất lưỡng tính.",
    recipe: { Zn: 1, O: 2, H: 2 },
    type: "Hợp chất",
  },
  {
    id: "zns",
    name: "Kẽm Sunfua",
    formula: "ZnS",
    desc: "Chất phát quang trong bóng tối.",
    recipe: { Zn: 1, S: 1 },
    type: "Hợp chất",
  },
  {
    id: "zn3po42",
    name: "Kẽm Photphat",
    formula: "Zn₃(PO₄)₂",
    desc: "Lớp lót sơn chống rỉ.",
    recipe: { Zn: 3, P: 2, O: 8 },
    type: "Hợp chất",
  },
  {
    id: "h2",
    name: "Khí Hydro",
    formula: "H₂",
    desc: "Nhiên liệu sạch, nhẹ nhất.",
    recipe: { H: 2 },
    type: "Đơn chất",
  },
  {
    id: "n2",
    name: "Khí Nitơ",
    formula: "N₂",
    desc: "Chiếm 78% không khí.",
    recipe: { N: 2 },
    type: "Đơn chất",
  },
  {
    id: "o3",
    name: "Ozon",
    formula: "O₃",
    desc: "Bảo vệ Trái đất khỏi tia cực tím.",
    recipe: { O: 3 },
    type: "Đơn chất",
  },
  {
    id: "br2",
    name: "Brom lỏng",
    formula: "Br₂",
    desc: "Chất lỏng màu đỏ nâu dễ bay hơi.",
    recipe: { Br: 2 },
    type: "Đơn chất",
  },
  {
    id: "i2",
    name: "Iốt rắn",
    formula: "I₂",
    desc: "Tinh thể tím đen, thăng hoa.",
    recipe: { I: 2 },
    type: "Đơn chất",
  },
  {
    id: "p4",
    name: "Photpho trắng",
    formula: "P₄",
    desc: "Tự cháy trong không khí.",
    recipe: { P: 4 },
    type: "Đơn chất",
  },

  // --- OXIT ---
  {
    id: "co",
    name: "Cacbon Monoxit",
    formula: "CO",
    desc: "Khí cực độc không màu.",
    recipe: { C: 1, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "so2",
    name: "Lưu huỳnh đioxit",
    formula: "SO₂",
    desc: "Khí mùi hắc, gây mưa axit.",
    recipe: { S: 1, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "so3",
    name: "Lưu huỳnh trioxit",
    formula: "SO₃",
    desc: "Chất trung gian sản xuất axit sunfuric.",
    recipe: { S: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "sio2",
    name: "Silic đioxit",
    formula: "SiO₂",
    desc: "Thành phần chính của cát và thạch anh.",
    recipe: { Si: 1, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "al2o3",
    name: "Nhôm oxit",
    formula: "Al₂O₃",
    desc: "Lớp màng bảo vệ nhôm, thành phần đá ruby.",
    recipe: { Al: 2, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "zno",
    name: "Kẽm oxit",
    formula: "ZnO",
    desc: "Dùng trong kem chống nắng.",
    recipe: { Zn: 1, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "fe3o4",
    name: "Oxit sắt từ",
    formula: "Fe₃O₄",
    desc: "Quặng manhetit có từ tính.",
    recipe: { Fe: 3, O: 4 },
    type: "Hợp chất",
  },

  // --- AXIT ---
  {
    id: "h2so4",
    name: "Axit Sunfuric",
    formula: "H₂SO₄",
    desc: "Hóa chất công nghiệp quan trọng nhất.",
    recipe: { H: 2, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "hno3",
    name: "Axit Nitric",
    formula: "HNO₃",
    desc: "Axit mạnh, dùng chế tạo thuốc nổ.",
    recipe: { H: 1, N: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "h3po4",
    name: "Axit Photphoric",
    formula: "H₃PO₄",
    desc: "Có trong nước ngọt có ga.",
    recipe: { H: 3, P: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "h2co3",
    name: "Axit Cacbonic",
    formula: "H₂CO₃",
    desc: "Có trong nước soda.",
    recipe: { H: 2, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "hf",
    name: "Axit Flohiđric",
    formula: "HF",
    desc: "Ăn mòn thủy tinh.",
    recipe: { H: 1, F: 1 },
    type: "Hợp chất",
  },
  {
    id: "h2s",
    name: "Hiđro Sunfua",
    formula: "H₂S",
    desc: "Mùi trứng thối đặc trưng.",
    recipe: { H: 2, S: 1 },
    type: "Hợp chất",
  },

  // --- BAZƠ ---
  {
    id: "koh",
    name: "Kali Hiđroxit",
    formula: "KOH",
    desc: "Kiềm mạnh, dùng làm xà phòng lỏng.",
    recipe: { K: 1, O: 1, H: 1 },
    type: "Hợp chất",
  },
  {
    id: "caoh2",
    name: "Canxi Hiđroxit",
    formula: "Ca(OH)₂",
    desc: "Vôi tôi, dùng trong xây dựng.",
    recipe: { Ca: 1, O: 2, H: 2 },
    type: "Hợp chất",
  },
  {
    id: "baoh2",
    name: "Bari Hiđroxit",
    formula: "Ba(OH)₂",
    desc: "Kiềm thổ mạnh.",
    recipe: { Ba: 1, O: 2, H: 2 },
    type: "Hợp chất",
  },
  {
    id: "aloh3",
    name: "Nhôm Hiđroxit",
    formula: "Al(OH)₃",
    desc: "Kết tủa keo trắng.",
    recipe: { Al: 1, O: 3, H: 3 },
    type: "Hợp chất",
  },
  {
    id: "feoh3",
    name: "Sắt(III) Hiđroxit",
    formula: "Fe(OH)₃",
    desc: "Kết tủa màu nâu đỏ.",
    recipe: { Fe: 1, O: 3, H: 3 },
    type: "Hợp chất",
  },
  {
    id: "cuoh2",
    name: "Đồng(II) Hiđroxit",
    formula: "Cu(OH)₂",
    desc: "Kết tủa màu xanh lam.",
    recipe: { Cu: 1, O: 2, H: 2 },
    type: "Hợp chất",
  },

  // --- MUỐI (Các loại đặc biệt) ---
  {
    id: "kno3",
    name: "Kali Nitrat",
    formula: "KNO₃",
    desc: "Thuốc súng đen.",
    recipe: { K: 1, N: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "cuso4",
    name: "Đồng Sunfat",
    formula: "CuSO₄",
    desc: "Phèn xanh, diệt nấm mốc.",
    recipe: { Cu: 1, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "agno3",
    name: "Bạc Nitrat",
    formula: "AgNO₃",
    desc: "Thuốc thử nhận biết muối clorua.",
    recipe: { Ag: 1, N: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "bacl2",
    name: "Bari Clorua",
    formula: "BaCl₂",
    desc: "Thuốc thử nhận biết gốc sunfat.",
    recipe: { Ba: 1, Cl: 2 },
    type: "Hợp chất",
  },
  {
    id: "na2co3",
    name: "Natri Cacbonat",
    formula: "Na₂CO₃",
    desc: "Soda công nghiệp, làm thủy tinh.",
    recipe: { Na: 2, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "nh4cl",
    name: "Amoni Clorua",
    formula: "NH₄Cl",
    desc: "Muối lạnh, dùng trong hàn kim loại.",
    recipe: { N: 1, H: 4, Cl: 1 },
    type: "Hợp chất",
  },
  {
    id: "cac2",
    name: "Canxi Cacbua",
    formula: "CaC₂",
    desc: "Đất đèn, dùng để tạo khí axetilen.",
    recipe: { Ca: 1, C: 2 },
    type: "Hợp chất",
  },
  {
    id: "kmno4",
    name: "Kali Pemanganat",
    formula: "KMnO₄",
    desc: "Thuốc tím, sát trùng mạnh.",
    recipe: { K: 1, Mn: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "kclo3",
    name: "Kali Clorat",
    formula: "KClO₃",
    desc: "Chất oxi hóa trong diêm, pháo.",
    recipe: { K: 1, Cl: 1, O: 3 },
    type: "Hợp chất",
  },

  // --- HÓA HỮU CƠ (Cơ bản) ---
  {
    id: "c2h2",
    name: "Axetilen",
    formula: "C₂H₂",
    desc: "Khí dùng để hàn cắt kim loại.",
    recipe: { C: 2, H: 2 },
    type: "Hợp chất",
  },
  {
    id: "c2h4",
    name: "Etilen",
    formula: "C₂H₄",
    desc: "Khí làm chín trái cây.",
    recipe: { C: 2, H: 4 },
    type: "Hợp chất",
  },
  {
    id: "c6h6",
    name: "Benzen",
    formula: "C₆H₆",
    desc: "Dung môi hữu cơ vòng thơm.",
    recipe: { C: 6, H: 6 },
    type: "Hợp chất",
  },
  {
    id: "c2h5oh",
    name: "Etanol",
    formula: "C₂H₅OH",
    desc: "Cồn thực phẩm, nhiên liệu sinh học.",
    recipe: { C: 2, H: 6, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "ch3oh",
    name: "Metanol",
    formula: "CH₃OH",
    desc: "Cồn công nghiệp (rất độc).",
    recipe: { C: 1, H: 4, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "ch3cooh",
    name: "Axit Axetic",
    formula: "CH₃COOH",
    desc: "Thành phần chính của giấm ăn.",
    recipe: { C: 2, H: 4, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "c6h12o6",
    name: "Glucozơ",
    formula: "C₆H₁₂O₆",
    desc: "Đường nho, nguồn năng lượng cơ thể.",
    recipe: { C: 6, H: 12, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "c12h22o11",
    name: "Saccarozơ",
    formula: "C₁₂H₂₂O₁₁",
    desc: "Đường kính (đường mía).",
    recipe: { C: 12, H: 22, O: 11 },
    type: "Hợp chất",
  },
  {
    id: "hcho",
    name: "Focmon",
    formula: "HCHO",
    desc: "Dùng ngâm xác động vật.",
    recipe: { C: 1, H: 2, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "c3h8",
    name: "Propan",
    formula: "C₃H₈",
    desc: "Khí gas đun nấu.",
    recipe: { C: 3, H: 8 },
    type: "Hợp chất",
  },
  {
    id: "c4h10",
    name: "Butan",
    formula: "C₄H₁₀",
    desc: "Khí gas bật lửa.",
    recipe: { C: 4, H: 10 },
    type: "Hợp chất",
  },
  // --- SẮT (Fe) ---
  {
    id: "fecl2",
    name: "Sắt(II) Clorua",
    formula: "FeCl₂",
    desc: "Dạng khan màu vàng, dùng xử lý nước thải.",
    recipe: { Fe: 1, Cl: 2 },
    type: "Hợp chất",
  },
  {
    id: "fecl3",
    name: "Sắt(III) Clorua",
    formula: "FeCl₃",
    desc: "Dùng khắc mạch điện tử (PCB).",
    recipe: { Fe: 1, Cl: 3 },
    type: "Hợp chất",
  },
  {
    id: "fe(oh)2",
    name: "Sắt(II) Hiđroxit",
    formula: "Fe(OH)₂",
    desc: "Kết tủa trắng xanh, dễ bị oxi hóa.",
    recipe: { Fe: 1, O: 2, H: 2 },
    type: "Hợp chất",
  },
  {
    id: "fe(oh)3",
    name: "Sắt(III) Hiđroxit",
    formula: "Fe(OH)₃",
    desc: "Kết tủa nâu đỏ đặc trưng.",
    recipe: { Fe: 1, O: 3, H: 3 },
    type: "Hợp chất",
  },
  {
    id: "feso4",
    name: "Sắt(II) Sunfat",
    formula: "FeSO₄",
    desc: "Phèn xanh, bổ sung sắt cho cây trồng.",
    recipe: { Fe: 1, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "fe2(so4)3",
    name: "Sắt(III) Sunfat",
    formula: "Fe₂(SO₄)₃",
    desc: "Dùng trong sản xuất thuốc nhuộm.",
    recipe: { Fe: 2, S: 3, O: 12 },
    type: "Hợp chất",
  },
  {
    id: "feco3",
    name: "Sắt(II) Cacbonat",
    formula: "FeCO₃",
    desc: "Quặng siderit.",
    recipe: { Fe: 1, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "feno33",
    name: "Sắt(III) Nitrat",
    formula: "Fe(NO₃)₃",
    desc: "Chất xúc tác và chất cầm màu.",
    recipe: { Fe: 1, N: 3, O: 9 },
    type: "Hợp chất",
  },
  {
    id: "fes",
    name: "Sắt(II) Sunfua",
    formula: "FeS",
    desc: "Dùng điều chế H₂S trong phòng thí nghiệm.",
    recipe: { Fe: 1, S: 1 },
    type: "Hợp chất",
  },
  {
    id: "fe2s3",
    name: "Sắt(III) Sunfua",
    formula: "Fe₂S₃",
    desc: "Rất không bền, dễ phân hủy.",
    recipe: { Fe: 2, S: 3 },
    type: "Hợp chất",
  },

  // --- ĐỒNG (Cu) ---
  {
    id: "cu2o",
    name: "Đồng(I) Oxit",
    formula: "Cu₂O",
    desc: "Dùng làm chất màu cho thủy tinh, gốm sứ.",
    recipe: { Cu: 2, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "cuo",
    name: "Đồng(II) Oxit",
    formula: "CuO",
    desc: "Chất màu đen, dùng trong gốm sứ.",
    recipe: { Cu: 1, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "cucl",
    name: "Đồng(I) Clorua",
    formula: "CuCl",
    desc: "Chất xúc tác hấp thụ CO.",
    recipe: { Cu: 1, Cl: 1 },
    type: "Hợp chất",
  },
  {
    id: "cucl2",
    name: "Đồng(II) Clorua",
    formula: "CuCl₂",
    desc: "Thuốc nhuộm và thuốc trừ sâu.",
    recipe: { Cu: 1, Cl: 2 },
    type: "Hợp chất",
  },
  {
    id: "cu(oh)2",
    name: "Đồng(II) Hiđroxit",
    formula: "Cu(OH)₂",
    desc: "Kết tủa xanh lam, dùng trong thuốc trừ nấm.",
    recipe: { Cu: 1, O: 2, H: 2 },
    type: "Hợp chất",
  },
  {
    id: "cu(no3)2",
    name: "Đồng(II) Nitrat",
    formula: "Cu(NO₃)₂",
    desc: "Chất tạo màu xanh trong pháo hoa.",
    recipe: { Cu: 1, N: 2, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "cuco3",
    name: "Đồng(II) Cacbonat",
    formula: "CuCO₃",
    desc: "Chất màu xanh lục của đồng bị oxi hóa.",
    recipe: { Cu: 1, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "cus",
    name: "Đồng(II) Sunfua",
    formula: "CuS",
    desc: "Quặng đồng, chất bán dẫn.",
    recipe: { Cu: 1, S: 1 },
    type: "Hợp chất",
  },

  // --- BẠC (Ag) ---
  {
    id: "agbr",
    name: "Bạc Bromua",
    formula: "AgBr",
    desc: "Chất cảm quang chính trong phim ảnh.",
    recipe: { Ag: 1, Br: 1 },
    type: "Hợp chất",
  },
  {
    id: "agicn",
    name: "Bạc Iotua",
    formula: "AgI",
    desc: "Dùng tạo mưa nhân tạo (gieo hạt mây).",
    recipe: { Ag: 1, I: 1 },
    type: "Hợp chất",
  },
  {
    id: "agcl",
    name: "Bạc Clorua",
    formula: "AgCl",
    desc: "Kết tủa trắng, nhạy cảm với ánh sáng.",
    recipe: { Ag: 1, Cl: 1 },
    type: "Hợp chất",
  },
  {
    id: "agno3",
    name: "Bạc Nitrat",
    formula: "AgNO₃",
    desc: "Thường gọi là 'bút thử bạc'.",
    recipe: { Ag: 1, N: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "ag2s",
    name: "Bạc Sunfua",
    formula: "Ag₂S",
    desc: "Chất gây ra hiện tượng bạc bị xỉn màu.",
    recipe: { Ag: 2, S: 1 },
    type: "Hợp chất",
  },

  // --- VÀNG (Au) ---
  {
    id: "haucl4",
    name: "Axit Cloruauric",
    formula: "HAuCl₄",
    desc: "Tiền chất để điều chế Vàng.",
    recipe: { H: 1, Au: 1, Cl: 4 },
    type: "Hợp chất",
  },
  {
    id: "au2o3",
    name: "Vàng(III) Oxit",
    formula: "Au₂O₃",
    desc: "Oxit vàng, không bền nhiệt.",
    recipe: { Au: 2, O: 3 },
    type: "Hợp chất",
  },

  // --- THỦY NGÂN (Hg) ---
  {
    id: "hgo",
    name: "Thủy ngân(II) Oxit",
    formula: "HgO",
    desc: "Chất rắn màu đỏ, độc.",
    recipe: { Hg: 1, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "hgs",
    name: "Thủy ngân(II) Sunfua",
    formula: "HgS",
    desc: "Bột chu sa màu đỏ, chất độc.",
    recipe: { Hg: 1, S: 1 },
    type: "Hợp chất",
  },
  {
    id: "hgcl2",
    name: "Thủy ngân(II) Clorua",
    formula: "HgCl₂",
    desc: "Sublimat ăn mòn (chất cực độc).",
    recipe: { Hg: 1, Cl: 2 },
    type: "Hợp chất",
  },

  // --- CROM (Cr) & MANGAN (Mn) ---
  {
    id: "cro3",
    name: "Crom(VI) Oxit",
    formula: "CrO₃",
    desc: "Chất tạo màu cho Chrome plating.",
    recipe: { Cr: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "cr2o3",
    name: "Crom(III) Oxit",
    formula: "Cr₂O₃",
    desc: "Chất màu xanh lá cây.",
    recipe: { Cr: 2, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "mncl2",
    name: "Mangan(II) Clorua",
    formula: "MnCl₂",
    desc: "Dùng trong pin khô.",
    recipe: { Mn: 1, Cl: 2 },
    type: "Hợp chất",
  },
  {
    id: "mno2",
    name: "Mangan Đioxit",
    formula: "MnO₂",
    desc: "Chất xúc tác trong pin Leclanché.",
    recipe: { Mn: 1, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "kmno4",
    name: "Kali Pemanganat",
    formula: "KMnO₄",
    desc: "Thuốc tím, chất khử trùng mạnh.",
    recipe: { K: 1, Mn: 1, O: 4 },
    type: "Hợp chất",
  },

  // --- CHÌ (Pb) ---
  {
    id: "pbo",
    name: "Chì(II) Oxit",
    formula: "PbO",
    desc: "Dùng trong sản xuất thủy tinh chì.",
    recipe: { Pb: 1, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "pbcl2",
    name: "Chì(II) Clorua",
    formula: "PbCl₂",
    desc: "Muối chì ít tan trong nước lạnh.",
    recipe: { Pb: 1, Cl: 2 },
    type: "Hợp chất",
  },
  {
    id: "pbso4",
    name: "Chì(II) Sunfat",
    formula: "PbSO₄",
    desc: "Tạo thành khi ắc quy chì phóng điện.",
    recipe: { Pb: 1, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "pbco3",
    name: "Chì(II) Cacbonat",
    formula: "PbCO₃",
    desc: "Bột màu trắng, độc.",
    recipe: { Pb: 1, C: 1, O: 3 },
    type: "Hợp chất",
  },

  // --- THIẾC (Sn) ---
  {
    id: "sncl2",
    name: "Thiếc(II) Clorua",
    formula: "SnCl₂",
    desc: "Dùng làm chất khử và chất nhạy sáng.",
    recipe: { Sn: 1, Cl: 2 },
    type: "Hợp chất",
  },
  {
    id: "sno2",
    name: "Thiếc Đioxit",
    formula: "SnO₂",
    desc: "Dùng trong men gốm, sứ.",
    recipe: { Sn: 1, O: 2 },
    type: "Hợp chất",
  },

  // --- SILIC (Si) ---
  {
    id: "sicl4",
    name: "Silic Tetraclorua",
    formula: "SiCl₄",
    desc: "Dùng sản xuất silic tinh khiết.",
    recipe: { Si: 1, Cl: 4 },
    type: "Hợp chất",
  },
  {
    id: "sih4",
    name: "Silan",
    formula: "SiH₄",
    desc: "Khí tự bốc cháy, dùng trong ngành bán dẫn.",
    recipe: { Si: 1, H: 4 },
    type: "Hợp chất",
  },

  // --- BORON (B) ---
  {
    id: "b2o3",
    name: "Bo Trioxit",
    formula: "B₂O₃",
    desc: "Thành phần của thủy tinh borosilicate.",
    recipe: { B: 2, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "h3bo3",
    name: "Axit Boric",
    formula: "H₃BO₃",
    desc: "Thuốc sát trùng và trừ sâu.",
    recipe: { H: 3, B: 1, O: 3 },
    type: "Hợp chất",
  },

  // --- PHOTPHO (P) ---
  {
    id: "hpo3",
    name: "Axit Metaphotphoric",
    formula: "HPO₃",
    desc: "Chất hút ẩm mạnh.",
    recipe: { H: 1, P: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "pcl3",
    name: "Photpho Triclorua",
    formula: "PCl₃",
    desc: "Chất lỏng không màu, dùng trong hóa hữu cơ.",
    recipe: { P: 1, Cl: 3 },
    type: "Hợp chất",
  },
  {
    id: "pcl5",
    name: "Photpho Pentaclorua",
    formula: "PCl₅",
    desc: "Tác nhân clo hóa mạnh.",
    recipe: { P: 1, Cl: 5 },
    type: "Hợp chất",
  },

  // --- LƯU HUỲNH (S) ---
  {
    id: "h2so3",
    name: "Axit Sunfurơ",
    formula: "H₂SO₃",
    desc: "Axit yếu, chỉ tồn tại trong dung dịch.",
    recipe: { H: 2, S: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "cs2",
    name: "Cacbon Đisunfua",
    formula: "CS₂",
    desc: "Dung môi không phân cực, độc.",
    recipe: { C: 1, S: 2 },
    type: "Hợp chất",
  },
  {
    id: "h2s2o3",
    name: "Axit Thiosunfuric",
    formula: "H₂S₂O₃",
    desc: "Muối Natri thiosunfat dùng trong nhiếp ảnh.",
    recipe: { H: 2, S: 2, O: 3 },
    type: "Hợp chất",
  },

  // --- CLO (Cl) ---
  {
    id: "hclo",
    name: "Axit Hipoclorơ",
    formula: "HClO",
    desc: "Thành phần chính của nước Javel.",
    recipe: { H: 1, Cl: 1, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "hclo3",
    name: "Axit Cloric",
    formula: "HClO₃",
    desc: "Axit mạnh, chất oxy hóa.",
    recipe: { H: 1, Cl: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "hclo4",
    name: "Axit Pecloric",
    formula: "HClO₄",
    desc: "Một trong những axit mạnh nhất.",
    recipe: { H: 1, Cl: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "cl2o7",
    name: "Điclo Heptaoxit",
    formula: "Cl₂O₇",
    desc: "Oxit axit của axit pecloric.",
    recipe: { Cl: 2, O: 7 },
    type: "Hợp chất",
  }, // --- ANKAN (Dãy đồng đẳng Metan) ---
  {
    id: "c5h12",
    name: "Pentan",
    formula: "C₅H₁₂",
    desc: "Thành phần của xăng, dễ bay hơi.",
    recipe: { C: 5, H: 12 },
    type: "Hợp chất",
  },
  {
    id: "c6h14",
    name: "Hexan",
    formula: "C₆H₁₄",
    desc: "Dung môi không phân cực phổ biến.",
    recipe: { C: 6, H: 14 },
    type: "Hợp chất",
  },
  {
    id: "c7h16",
    name: "Heptan",
    formula: "C₇H₁₆",
    desc: "Chất chuẩn để xác định trị số Octan.",
    recipe: { C: 7, H: 16 },
    type: "Hợp chất",
  },
  {
    id: "c8h18",
    name: "Octan",
    formula: "C₈H₁₈",
    desc: "Thành phần chính của xăng chất lượng cao.",
    recipe: { C: 8, H: 18 },
    type: "Hợp chất",
  },
  {
    id: "c9h20",
    name: "Nonan",
    formula: "C₉H₂₀",
    desc: "Dùng làm chất hoạt động bề mặt.",
    recipe: { C: 9, H: 20 },
    type: "Hợp chất",
  },
  {
    id: "c10h22",
    name: "Đecan",
    formula: "C₁₀H₂₂",
    desc: "Dùng trong dầu hỏa.",
    recipe: { C: 10, H: 22 },
    type: "Hợp chất",
  },

  // --- ANKEN & ANKIN (Không no) ---
  {
    id: "c3h6",
    name: "Propen",
    formula: "C₃H₆",
    desc: "Khí dùng sản xuất nhựa Polypropylene (PP).",
    recipe: { C: 3, H: 6 },
    type: "Hợp chất",
  },
  {
    id: "c4h8",
    name: "Buten",
    formula: "C₄H₈",
    desc: "Nguyên liệu sản xuất cao su tổng hợp.",
    recipe: { C: 4, H: 8 },
    type: "Hợp chất",
  },
  {
    id: "c3h4",
    name: "Propin",
    formula: "C₃H₄",
    desc: "Một loại Ankin, dùng làm nhiên liệu.",
    recipe: { C: 3, H: 4 },
    type: "Hợp chất",
  },
  {
    id: "c4h6",
    name: "Butađien",
    formula: "C₄H₆",
    desc: "Quan trọng để sản xuất cao su SBR.",
    recipe: { C: 4, H: 6 },
    type: "Hợp chất",
  },

  // --- ANCOL & PHENOL ---
  {
    id: "c3h7oh",
    name: "Propanol",
    formula: "C₃H₇OH",
    desc: "Cồn sát trùng, dễ cháy.",
    recipe: { C: 3, H: 8, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "c4h9oh",
    name: "Butanol",
    formula: "C₄H₉OH",
    desc: "Dung môi cho sơn và vecni.",
    recipe: { C: 4, H: 10, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "c2h4oh2",
    name: "Etilen Glicol",
    formula: "C₂H₄(OH)₂",
    desc: "Chất chống đông cho ô tô.",
    recipe: { C: 2, H: 6, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "c3h5oh3",
    name: "Glixerol",
    formula: "C₃H₅(OH)₃",
    desc: "Dầu béo, làm chất giữ ẩm, sản xuất thuốc nổ.",
    recipe: { C: 3, H: 8, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "c6h5oh",
    name: "Phenol",
    formula: "C₆H₅OH",
    desc: "Axit yếu, dùng làm chất khử trùng (Carbolic Acid).",
    recipe: { C: 6, H: 6, O: 1 },
    type: "Hợp chất",
  },

  // --- AXIT CARBOXYLIC & ESTER ---
  {
    id: "hcooh",
    name: "Axit Fomic",
    formula: "HCOOH",
    desc: "Axit có trong nọc kiến.",
    recipe: { H: 2, C: 1, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "c3h7cooh",
    name: "Axit Butiric",
    formula: "C₃H₇COOH",
    desc: "Gây mùi bơ bị ôi.",
    recipe: { C: 4, H: 8, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "c17h35cooh",
    name: "Axit Stearic",
    formula: "C₁₇H₃₅COOH",
    desc: "Dùng làm nến và xà phòng cứng.",
    recipe: { C: 18, H: 36, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "c17h33cooh",
    name: "Axit Oleic",
    formula: "C₁₇H₃₃COOH",
    desc: "Axit béo không no trong dầu ô liu.",
    recipe: { C: 18, H: 34, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "ch3cooc2h5",
    name: "Etyl Axetat",
    formula: "CH₃COOC₂H₅",
    desc: "Mùi hương trái cây, dùng làm dung môi.",
    recipe: { C: 4, H: 8, O: 2 },
    type: "Hợp chất",
  },

  // --- AMIN & AMIT ---
  {
    id: "ch3nh2",
    name: "Metylamin",
    formula: "CH₃NH₂",
    desc: "Amin đơn giản nhất, mùi tanh cá.",
    recipe: { C: 1, H: 5, N: 1 },
    type: "Hợp chất",
  },
  {
    id: "c6h5nh2",
    name: "Anilin",
    formula: "C₆H₅NH₂",
    desc: "Nguyên liệu sản xuất thuốc nhuộm Azo.",
    recipe: { C: 6, H: 7, N: 1 },
    type: "Hợp chất",
  },
  {
    id: "ch3conh2",
    name: "Axetamit",
    formula: "CH₃CONH₂",
    desc: "Amit đơn giản, dung môi hữu cơ.",
    recipe: { C: 2, H: 5, N: 1, O: 1 },
    type: "Hợp chất",
  },

  // --- MUỐI ĐA HÓA TRỊ (Phosphate, Silicate, Carbonate, Nitrite) ---
  {
    id: "na3po4",
    name: "Natri Photphat",
    formula: "Na₃PO₄",
    desc: "Chất tẩy rửa, điều chỉnh độ pH.",
    recipe: { Na: 3, P: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "k3po4",
    name: "Kali Photphat",
    formula: "K₃PO₄",
    desc: "Phân bón, phụ gia thực phẩm.",
    recipe: { K: 3, P: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "ca3po42",
    name: "Canxi Photphat",
    formula: "Ca₃(PO₄)₂",
    desc: "Nguyên liệu sản xuất phân lân.",
    recipe: { Ca: 3, P: 2, O: 8 },
    type: "Hợp chất",
  },
  {
    id: "mg3po42",
    name: "Magiê Photphat",
    formula: "Mg₃(PO₄)₂",
    desc: "Có trong sữa Magnesia.",
    recipe: { Mg: 3, P: 2, O: 8 },
    type: "Hợp chất",
  },

  {
    id: "k2sio3",
    name: "Kali Silicat",
    formula: "K₂SiO₃",
    desc: "Thủy tinh lỏng (hồ nước).",
    recipe: { K: 2, Si: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "na2sio3",
    name: "Natri Silicat",
    formula: "Na₂SiO₃",
    desc: "Dùng làm chất kết dính, xi măng.",
    recipe: { Na: 2, Si: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "caio3",
    name: "Canxi Iotat",
    formula: "Ca(IO₃)₂",
    desc: "Dùng để bổ sung Iốt trong thức ăn.",
    recipe: { Ca: 1, I: 2, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "na2co3",
    name: "Natri Cacbonat",
    formula: "Na₂CO₃",
    desc: "Soda, làm thủy tinh và bột giặt.",
    recipe: { Na: 2, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "k2co3",
    name: "Kali Cacbonat",
    formula: "K₂CO₃",
    desc: "Thành phần tro thực vật (Potash).",
    recipe: { K: 2, C: 1, O: 3 },
    type: "Hợp chất",
  },

  // --- CHẤT KHÁC (Đa dạng) ---
  {
    id: "c6h8o7",
    name: "Axit Citric",
    formula: "C₆H₈O₇",
    desc: "Axit tạo vị chua trong chanh.",
    recipe: { C: 6, H: 8, O: 7 },
    type: "Hợp chất",
  },
  {
    id: "h2c2o4",
    name: "Axit Oxalic",
    formula: "H₂C₂O₄",
    desc: "Có trong rau chân vịt, dùng tẩy gỉ sét.",
    recipe: { H: 2, C: 2, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "hcn",
    name: "Axit Xyanhiđric",
    formula: "HCN",
    desc: "Chất lỏng cực độc, mùi hạnh nhân.",
    recipe: { H: 1, C: 1, N: 1 },
    type: "Hợp chất",
  },
  {
    id: "nh4no3",
    name: "Amoni Nitrat",
    formula: "NH₄NO₃",
    desc: "Phân bón, thành phần thuốc nổ.",
    recipe: { N: 2, H: 4, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "h2o2",
    name: "Hiđro Peroxit",
    formula: "H₂O₂",
    desc: "Nước oxy già, chất tẩy rửa nhẹ.",
    recipe: { H: 2, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "cs2",
    name: "Cacbon Đisunfua",
    formula: "CS₂",
    desc: "Dung môi công nghiệp, độc.",
    recipe: { C: 1, S: 2 },
    type: "Hợp chất",
  },
  {
    id: "ch2o2",
    name: "Axit Fomic",
    formula: "HCOOH",
    desc: "Axit đơn giản nhất (tên khác: HCOOH).",
    recipe: { C: 1, H: 2, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "c4h10o",
    name: "Đietyl Ete",
    formula: "C₂H₅OC₂H₅",
    desc: "Thuốc gây mê cổ điển, dễ cháy.",
    recipe: { C: 4, H: 10, O: 1 },
    type: "Hợp chất",
  }, // --- AXIT BỀN & ANHYDRIT ---
  {
    id: "hno2",
    name: "Axit Nitrơ",
    formula: "HNO₂",
    desc: "Axit yếu, không bền, dùng điều chế muối nitrit.",
    recipe: { H: 1, N: 1, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "h2cro4",
    name: "Axit Cromic",
    formula: "H₂CrO₄",
    desc: "Axit mạnh, chất oxy hóa mạnh.",
    recipe: { H: 2, Cr: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "h2cr2o7",
    name: "Axit Đicromic",
    formula: "H₂Cr₂O₇",
    desc: "Chất oxy hóa mạnh, tồn tại trong dung dịch.",
    recipe: { H: 2, Cr: 2, O: 7 },
    type: "Hợp chất",
  },
  {
    id: "h2mno4",
    name: "Axit Manganic",
    formula: "H₂MnO₄",
    desc: "Không bền, tạo màu xanh lục.",
    recipe: { H: 2, Mn: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "h2c2o4",
    name: "Axit Oxalic",
    formula: "H₂C₂O₄",
    desc: "Dùng tẩy gỉ sét và thuốc nhuộm.",
    recipe: { H: 2, C: 2, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "co3o4",
    name: "Coban Oxit",
    formula: "Co₃O₄",
    desc: "Dùng làm chất xúc tác và chất tạo màu xanh.",
    recipe: { Co: 3, O: 4 },
    type: "Hợp chất",
  },

  // --- MUỐI PHỨC TẠP (Vài ví dụ) ---
  {
    id: "na2hpo4",
    name: "Natri Hiđrophotphat",
    formula: "Na₂HPO₄",
    desc: "Muối đệm, dùng trong y tế và thực phẩm.",
    recipe: { Na: 2, H: 1, P: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "nah2po4",
    name: "Natri Đihiđrophotphat",
    formula: "NaH₂PO₄",
    desc: "Dùng làm chất axit trong bột nở.",
    recipe: { Na: 1, H: 2, P: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "knao3s",
    name: "Natri Kali Sunfat",
    formula: "KNaSO₄",
    desc: "Muối kép của kali và natri.",
    recipe: { K: 1, Na: 1, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "kcr(so4)2",
    name: "Phèn Crom-Kali",
    formula: "KCr(SO₄)₂",
    desc: "Muối kép dùng trong thuộc da.",
    recipe: { K: 1, Cr: 1, S: 2, O: 8 },
    type: "Hợp chất",
  },
  {
    id: "nh4h2po4",
    name: "Amoni Đihiđrophotphat",
    formula: "NH₄H₂PO₄",
    desc: "Phân bón đạm-lân, chất chống cháy.",
    recipe: { N: 1, H: 6, P: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "na2s2o3",
    name: "Natri Thiosunfat",
    formula: "Na₂S₂O₃",
    desc: "Thuốc hãm ảnh, dùng giải độc Xyanua.",
    recipe: { Na: 2, S: 2, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "kscn",
    name: "Kali Thioxianat",
    formula: "KSCN",
    desc: "Thuốc thử nhận biết Sắt(III).",
    recipe: { K: 1, S: 1, C: 1, N: 1 },
    type: "Hợp chất",
  },

  // --- CARBOHYDRATE & ĐỒNG PHÂN HỮU CƠ ---
  {
    id: "c12h22o11_maltose",
    name: "Maltose",
    formula: "C₁₂H₂₂O₁₁",
    desc: "Đường mạch nha.",
    recipe: { C: 12, H: 22, O: 11 },
    type: "Hợp chất",
  },
  {
    id: "c12h22o11_lactose",
    name: "Lactose",
    formula: "C₁₂H₂₂O₁₁",
    desc: "Đường sữa.",
    recipe: { C: 12, H: 22, O: 11 },
    type: "Hợp chất",
  },
  {
    id: "c6h12o6_fructose",
    name: "Fructozơ",
    formula: "C₆H₁₂O₆",
    desc: "Đường trái cây.",
    recipe: { C: 6, H: 12, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "c6h12o6_galactose",
    name: "Galactozơ",
    formula: "C₆H₁₂O₆",
    desc: "Đường đơn của sữa.",
    recipe: { C: 6, H: 12, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "c2h6o_ether",
    name: "Đimetyl Ete",
    formula: "CH₃OCH₃",
    desc: "Đồng phân của Etanol, khí đẩy bình xịt.",
    recipe: { C: 2, H: 6, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "ch3cl",
    name: "Clometan",
    formula: "CH₃Cl",
    desc: "Khí làm lạnh cũ, chất gây mê nhẹ.",
    recipe: { C: 1, H: 3, Cl: 1 },
    type: "Hợp chất",
  },
  {
    id: "ch2cl2",
    name: "Điclometan",
    formula: "CH₂Cl₂",
    desc: "Dung môi tẩy sơn.",
    recipe: { C: 1, H: 2, Cl: 2 },
    type: "Hợp chất",
  },
  {
    id: "c3h8o_propanol",
    name: "Isopropanol",
    formula: "C₃H₇OH",
    desc: "Cồn tẩy rửa vết thương.",
    recipe: { C: 3, H: 8, O: 1 },
    type: "Hợp chất",
  },

  // --- HỢP CHẤT CÓ NITƠ & LƯU HUỲNH KHÁC ---
  {
    id: "no3",
    name: "Nitrat (Gốc)",
    formula: "NO₃⁻",
    desc: "Gốc phổ biến trong phân bón.",
    recipe: { N: 1, O: 3 },
    type: "hợp chất",
  },
  {
    id: "po4",
    name: "Photphat (Gốc)",
    formula: "PO₄³⁻",
    desc: "Gốc quan trọng trong DNA và ATP.",
    recipe: { P: 1, O: 4 },
    type: "hợp chất",
  },
  {
    id: "co3",
    name: "Cacbonat (Gốc)",
    formula: "CO₃²⁻",
    desc: "Gốc trong đá vôi và vỏ sò.",
    recipe: { C: 1, O: 3 },
    type: "hợp chất",
  },
  {
    id: "hno",
    name: "Nitroxyl",
    formula: "HNO",
    desc: "Hợp chất trung gian trong sinh học.",
    recipe: { H: 1, N: 1, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "n2o3",
    name: "Đinitơ Trioxit",
    formula: "N₂O₃",
    desc: "Anhydrit của axit nitrơ, màu xanh lam đậm.",
    recipe: { N: 2, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "n2o5",
    name: "Đinitơ Pentaoxit",
    formula: "N₂O₅",
    desc: "Anhydrit của axit nitric, chất oxy hóa mạnh.",
    recipe: { N: 2, O: 5 },
    type: "Hợp chất",
  },
  {
    id: "h2po2",
    name: "Axit Hipophotphorơ",
    formula: "H₃PO₂",
    desc: "Axit đơn chức, chất khử mạnh.",
    recipe: { H: 3, P: 1, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "h3po3",
    name: "Axit Photphorơ",
    formula: "H₃PO₃",
    desc: "Axit hai chức yếu.",
    recipe: { H: 3, P: 1, O: 3 },
    type: "Hợp chất",
  },

  // --- MUỐI CỦA THỦY TINH & GỐM SỨ ---
  {
    id: "k2sio3",
    name: "Kali Silicat",
    formula: "K₂SiO₃",
    desc: "Thủy tinh lỏng, dùng làm keo, chất độn.",
    recipe: { K: 2, Si: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "ba2sio4",
    name: "Bari Silicat",
    formula: "Ba₂SiO₄",
    desc: "Dùng trong sản xuất gốm sứ chịu nhiệt.",
    recipe: { Ba: 2, Si: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "pbcro4",
    name: "Chì(II) Cromat",
    formula: "PbCrO₄",
    desc: "Bột màu vàng tươi (Yellow chrome).",
    recipe: { Pb: 1, Cr: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "na4sio4",
    name: "Natri Orthosilicat",
    formula: "Na₄SiO₄",
    desc: "Chất tẩy rửa công nghiệp mạnh.",
    recipe: { Na: 4, Si: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "kno2",
    name: "Kali Nitrit",
    formula: "KNO₂",
    desc: "Bảo quản thực phẩm.",
    recipe: { K: 1, N: 1, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "na2o2",
    name: "Natri Peroxit",
    formula: "Na₂O₂",
    desc: "Chất oxy hóa mạnh, dùng làm chất tẩy.",
    recipe: { Na: 2, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "kmn",
    name: "Manganat Kali",
    formula: "K₂MnO₄",
    desc: "Dung dịch xanh lục, tiền chất KMnO4.",
    recipe: { K: 2, Mn: 1, O: 4 },
    type: "Hợp chất",
  },

  // --- HỢP CHẤT ĐƠN GIẢN HÓA TRỊ KHÁC (Đồng I, Thiếc II, vv)
  {
    id: "cul",
    name: "Đồng(I) Iotua",
    formula: "CuI",
    desc: "Dùng làm phụ gia thức ăn chăn nuôi.",
    recipe: { Cu: 1, I: 1 },
    type: "Hợp chất",
  },
  {
    id: "sncl4",
    name: "Thiếc(IV) Clorua",
    formula: "SnCl₄",
    desc: "Axit Lewis mạnh, dùng mạ thiếc.",
    recipe: { Sn: 1, Cl: 4 },
    type: "Hợp chất",
  },
  {
    id: "pbcl4",
    name: "Chì(IV) Clorua",
    formula: "PbCl₄",
    desc: "Chất lỏng màu vàng, không bền.",
    recipe: { Pb: 1, Cl: 4 },
    type: "Hợp chất",
  },
  {
    id: "hbr",
    name: "Axit Bromhiđric",
    formula: "HBr",
    desc: "Axit mạnh, dùng trong hóa hữu cơ.",
    recipe: { H: 1, Br: 1 },
    type: "Hợp chất",
  },
  {
    id: "hi",
    name: "Axit Iothiđric",
    formula: "HI",
    desc: "Axit mạnh nhất trong nhóm Halogen.",
    recipe: { H: 1, I: 1 },
    type: "Hợp chất",
  }, // --- ANKAN MỞ RỘNG (C11 - C20) ---
  {
    id: "c11h24",
    name: "Undecan",
    formula: "C₁₁H₂₄",
    desc: "Thành phần của dầu hỏa và dầu diesel.",
    recipe: { C: 11, H: 24 },
    type: "Hợp chất",
  },
  {
    id: "c12h26",
    name: "Đodecan",
    formula: "C₁₂H₂₆",
    desc: "Dung môi trong phòng thí nghiệm.",
    recipe: { C: 12, H: 26 },
    type: "Hợp chất",
  },
  {
    id: "c13h28",
    name: "Triđecan",
    formula: "C₁₃H₂₈",
    desc: "Dùng trong ngành hàng không.",
    recipe: { C: 13, H: 28 },
    type: "Hợp chất",
  },
  {
    id: "c14h30",
    name: "Tetrađecan",
    formula: "C₁₄H₃₀",
    desc: "Thành phần sáp nến.",
    recipe: { C: 14, H: 30 },
    type: "Hợp chất",
  },
  {
    id: "c15h32",
    name: "Pentađecan",
    formula: "C₁₅H₃₂",
    desc: "Thành phần sáp nến paraffin.",
    recipe: { C: 15, H: 32 },
    type: "Hợp chất",
  },
  {
    id: "c16h34",
    name: "Hexađecan",
    formula: "C₁₆H₃₄",
    desc: "Trị số Xetan (chất lượng dầu diesel).",
    recipe: { C: 16, H: 34 },
    type: "Hợp chất",
  },
  {
    id: "c17h36",
    name: "Heptađecan",
    formula: "C₁₇H₃₆",
    desc: "Hợp chất hydrocacbon béo.",
    recipe: { C: 17, H: 36 },
    type: "Hợp chất",
  },
  {
    id: "c18h38",
    name: "Octađecan",
    formula: "C₁₈H₃₈",
    desc: "Dùng trong dầu bôi trơn.",
    recipe: { C: 18, H: 38 },
    type: "Hợp chất",
  },
  {
    id: "c19h40",
    name: "Nonađecan",
    formula: "C₁₉H₄₀",
    desc: "Hydrocacbon chuỗi dài.",
    recipe: { C: 19, H: 40 },
    type: "Hợp chất",
  },
  {
    id: "c20h42",
    name: "Eicosan",
    formula: "C₂₀H₄₂",
    desc: "Thành phần sáp rắn.",
    recipe: { C: 20, H: 42 },
    type: "Hợp chất",
  },

  // --- AXIT BÉO (MUỐI) ---
  {
    id: "c15h31cooh",
    name: "Axit Palmitic",
    formula: "C₁₅H₃₁COOH",
    desc: "Axit béo no phổ biến trong dầu cọ.",
    recipe: { C: 16, H: 32, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "ch3coona",
    name: "Natri Axetat",
    formula: "CH₃COONa",
    desc: "Muối của giấm, dùng trong túi sưởi ấm.",
    recipe: { C: 2, H: 3, O: 2, Na: 1 },
    type: "Hợp chất",
  },
  {
    id: "ch3cook",
    name: "Kali Axetat",
    formula: "CH₃COOK",
    desc: "Chất chống đông thân thiện với môi trường.",
    recipe: { C: 2, H: 3, O: 2, K: 1 },
    type: "Hợp chất",
  },
  {
    id: "c17h35coona",
    name: "Natri Stearat",
    formula: "C₁₇H₃₅COONa",
    desc: "Muối của xà phòng cứng.",
    recipe: { C: 18, H: 35, O: 2, Na: 1 },
    type: "Hợp chất",
  },
  {
    id: "c17h35cook",
    name: "Kali Stearat",
    formula: "C₁₇H₃₅COOK",
    desc: "Muối của xà phòng mềm/lỏng.",
    recipe: { C: 18, H: 35, O: 2, K: 1 },
    type: "Hợp chất",
  },

  // --- HỢP CHẤT CÓ CLO & FLO HỮU CƠ ---
  {
    id: "ccl4",
    name: "Cacbon Tetraclorua",
    formula: "CCl₄",
    desc: "Dung môi không cháy, độc hại.",
    recipe: { C: 1, Cl: 4 },
    type: "Hợp chất",
  },
  {
    id: "chcl3",
    name: "Cloroform",
    formula: "CHCl₃",
    desc: "Dung môi, từng dùng làm thuốc mê.",
    recipe: { C: 1, H: 1, Cl: 3 },
    type: "Hợp chất",
  },
  {
    id: "c2f4",
    name: "Tetrafloeten",
    formula: "C₂F₄",
    desc: "Nguyên liệu sản xuất Teflon (chống dính).",
    recipe: { C: 2, F: 4 },
    type: "Hợp chất",
  },
  {
    id: "c6h5cl",
    name: "Clobenzen",
    formula: "C₆H₅Cl",
    desc: "Dung môi trong công nghiệp thuốc nhuộm.",
    recipe: { C: 6, H: 5, Cl: 1 },
    type: "Hợp chất",
  },

  // --- KIM LOẠI CHUYỂN TIẾP KHÁC (Nickel, Coban, Titan) ---
  {
    id: "nico3",
    name: "Niken(II) Cacbonat",
    formula: "NiCO₃",
    desc: "Dùng trong mạ điện và chất xúc tác.",
    recipe: { Ni: 1, C: 1, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "niso4",
    name: "Niken(II) Sunfat",
    formula: "NiSO₄",
    desc: "Dùng trong xi mạ Niken.",
    recipe: { Ni: 1, S: 1, O: 4 },
    type: "Hợp chất",
  },
  {
    id: "nicl2",
    name: "Niken(II) Clorua",
    formula: "NiCl₂",
    desc: "Muối Niken màu xanh lá cây.",
    recipe: { Ni: 1, Cl: 2 },
    type: "Hợp chất",
  },
  {
    id: "co(no3)2",
    name: "Coban(II) Nitrat",
    formula: "Co(NO₃)₂",
    desc: "Chất tạo màu xanh lam cho thủy tinh.",
    recipe: { Co: 1, N: 2, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "co2o3",
    name: "Coban(III) Oxit",
    formula: "Co₂O₃",
    desc: "Dùng trong điện cực pin.",
    recipe: { Co: 2, O: 3 },
    type: "Hợp chất",
  },
  {
    id: "tios2",
    name: "Titan Đisunfua",
    formula: "TiS₂",
    desc: "Vật liệu catot cho pin Lithium.",
    recipe: { Ti: 1, S: 2 },
    type: "Hợp chất",
  },
  {
    id: "ticl4",
    name: "Titan(IV) Clorua",
    formula: "TiCl₄",
    desc: "Dùng sản xuất Titan Đioxit.",
    recipe: { Ti: 1, Cl: 4 },
    type: "Hợp chất",
  },
  {
    id: "v2o5",
    name: "Vanađi(V) Oxit",
    formula: "V₂O₅",
    desc: "Chất xúc tác sản xuất Axit Sunfuric.",
    recipe: { V: 2, O: 5 },
    type: "Hợp chất",
  },
  {
    id: "zrcl4",
    name: "Zirconi(IV) Clorua",
    formula: "ZrCl₄",
    desc: "Tiền chất của Zirconi.",
    recipe: { Zr: 1, Cl: 4 },
    type: "Hợp chất",
  },
  {
    id: "pdcl2",
    name: "Palađi(II) Clorua",
    formula: "PdCl₂",
    desc: "Chất xúc tác phản ứng hữu cơ.",
    recipe: { Pd: 1, Cl: 2 },
    type: "Hợp chất",
  },

  // --- HỢP CHẤT CỦA BÁN KIM LOẠI/PHI KIM ---
  {
    id: "bcl3",
    name: "Bo Triclorua",
    formula: "BCl₃",
    desc: "Dùng trong khắc vật liệu bán dẫn.",
    recipe: { B: 1, Cl: 3 },
    type: "Hợp chất",
  },
  {
    id: "hcn",
    name: "Axit Xyanhiđric",
    formula: "HCN",
    desc: "Chất lỏng bay hơi cực độc, mùi hạnh nhân.",
    recipe: { H: 1, C: 1, N: 1 },
    type: "Hợp chất",
  },
  {
    id: "hclo2",
    name: "Axit Clorơ",
    formula: "HClO₂",
    desc: "Axit không bền, dùng tẩy trắng.",
    recipe: { H: 1, Cl: 1, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "si2h6",
    name: "Đisilan",
    formula: "Si₂H₆",
    desc: "Đồng đẳng của Silan, chất khí dễ cháy.",
    recipe: { Si: 2, H: 6 },
    type: "Hợp chất",
  },
  {
    id: "h2te",
    name: "Hiđro Telurua",
    formula: "H₂Te",
    desc: "Khí độc, có mùi tỏi.",
    recipe: { H: 2, Te: 1 },
    type: "Hợp chất",
  },
  {
    id: "h2se",
    name: "Hiđro Selenua",
    formula: "H₂Se",
    desc: "Khí độc hơn H₂S.",
    recipe: { H: 2, Se: 1 },
    type: "Hợp chất",
  },

  // --- MUỐI SUNFUA & IOTUA KHÁC ---
  {
    id: "nis",
    name: "Niken(II) Sunfua",
    formula: "NiS",
    desc: "Kết tủa đen, dùng làm xúc tác.",
    recipe: { Ni: 1, S: 1 },
    type: "Hợp chất",
  },
  {
    id: "cos",
    name: "Coban(II) Sunfua",
    formula: "CoS",
    desc: "Kết tủa đen, dùng làm chất màu.",
    recipe: { Co: 1, S: 1 },
    type: "Hợp chất",
  },
  {
    id: "mgs",
    name: "Magiê Sunfua",
    formula: "MgS",
    desc: "Tạo màu ánh xanh.",
    recipe: { Mg: 1, S: 1 },
    type: "Hợp chất",
  },
  {
    id: "hg2cl2",
    name: "Thủy ngân(I) Clorua",
    formula: "Hg₂Cl₂",
    desc: "Bột calomel, dùng làm thuốc xổ.",
    recipe: { Hg: 2, Cl: 2 },
    type: "Hợp chất",
  },
  {
    id: "zn3as2",
    name: "Kẽm Asenua",
    formula: "Zn₃As₂",
    desc: "Chất bán dẫn.",
    recipe: { Zn: 3, As: 2 },
    type: "Hợp chất",
  },

  // --- HỢP CHẤT THAY THẾ (Cần thêm để đạt 500+) ---
  // Muối Amoni (Ammonium)
  {
    id: "nh4cl",
    name: "Amoni Clorua",
    formula: "NH₄Cl",
    desc: "Muối lạnh, dùng làm chất điện giải.",
    recipe: { N: 1, H: 4, Cl: 1 },
    type: "Hợp chất",
  },
  {
    id: "nh4br",
    name: "Amoni Bromua",
    formula: "NH₄Br",
    desc: "Thuốc an thần.",
    recipe: { N: 1, H: 4, Br: 1 },
    type: "Hợp chất",
  },
  {
    id: "nh4i",
    name: "Amoni Iotua",
    formula: "NH₄I",
    desc: "Dùng trong nhiếp ảnh và y học.",
    recipe: { N: 1, H: 4, I: 1 },
    type: "Hợp chất",
  },
  {
    id: "nh4oh",
    name: "Amoni Hiđroxit",
    formula: "NH₄OH",
    desc: "Nước Amoniac, dung dịch tẩy rửa.",
    recipe: { N: 1, H: 5, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "nh4no2",
    name: "Amoni Nitrit",
    formula: "NH₄NO₂",
    desc: "Không bền, dùng điều chế N₂.",
    recipe: { N: 2, H: 4, O: 2 },
    type: "Hợp chất",
  },
  {
    id: "nh42co3",
    name: "Amoni Cacbonat",
    formula: "(NH₄)₂CO₃",
    desc: "Bột nở bánh quy.",
    recipe: { N: 2, H: 8, C: 1, O: 3 },
    type: "Hợp chất",
  },

  // Aldehyd và Cetone
  {
    id: "c2h4o",
    name: "Axetandehit",
    formula: "CH₃CHO",
    desc: "Chất lỏng dễ bay hơi, dung môi.",
    recipe: { C: 2, H: 4, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "c3h6o_aceton",
    name: "Axeton",
    formula: "CH₃COCH₃",
    desc: "Dung môi tẩy sơn móng tay.",
    recipe: { C: 3, H: 6, O: 1 },
    type: "Hợp chất",
  },
  {
    id: "c6h12o",
    name: "Xyclohexanol",
    formula: "C₆H₁₂O",
    desc: "Tiền chất sản xuất nylon.",
    recipe: { C: 6, H: 12, O: 1 },
    type: "Hợp chất",
  },

  // Một số Axit & Muối hữu cơ khác
  {
    id: "c6h8o6",
    name: "Axit Ascorbic",
    formula: "C₆H₈O₆",
    desc: "Vitamin C, chất chống oxy hóa.",
    recipe: { C: 6, H: 8, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "c4h6o6",
    name: "Axit Tactric",
    formula: "C₄H₆O₆",
    desc: "Axit trong nho và rượu vang.",
    recipe: { C: 4, H: 6, O: 6 },
    type: "Hợp chất",
  },
  {
    id: "c7h6o3",
    name: "Axit Salixylic",
    formula: "C₇H₆O₃",
    desc: "Thành phần thuốc Aspirin.",
    recipe: { C: 7, H: 6, O: 3 },
    type: "Hợp chất",
  }, // --- KIM LOẠI (Metals) ---
  {
    id: "fe",
    name: "Sắt",
    formula: "Fe",
    desc: "Kim loại quan trọng nhất, thành phần chính của thép.",
    recipe: { Fe: 1 },
    type: "Đơn chất",
  },
  {
    id: "al",
    name: "Nhôm",
    formula: "Al",
    desc: "Kim loại nhẹ, chống ăn mòn, dùng trong công nghiệp hàng không.",
    recipe: { Al: 1 },
    type: "Đơn chất",
  },
  {
    id: "cu",
    name: "Đồng",
    formula: "Cu",
    desc: "Dẫn điện và dẫn nhiệt tốt, dùng làm dây điện và hợp kim đồng thau.",
    recipe: { Cu: 1 },
    type: "Đơn chất",
  },
  {
    id: "au",
    name: "Vàng",
    formula: "Au",
    desc: "Kim loại quý, không bị oxy hóa, dùng làm trang sức và dự trữ.",
    recipe: { Au: 1 },
    type: "Đơn chất",
  },
  {
    id: "ag",
    name: "Bạc",
    formula: "Ag",
    desc: "Kim loại có tính dẫn điện tốt nhất, dùng trong nhiếp ảnh và điện tử.",
    recipe: { Ag: 1 },
    type: "Đơn chất",
  },
  {
    id: "na",
    name: "Natri",
    formula: "Na",
    desc: "Kim loại kiềm mềm, phản ứng mạnh với nước.",
    recipe: { Na: 1 },
    type: "Đơn chất",
  },
  {
    id: "k",
    name: "Kali",
    formula: "K",
    desc: "Kim loại kiềm, cần thiết cho chức năng tế bào và phân bón.",
    recipe: { K: 1 },
    type: "Đơn chất",
  },
  {
    id: "ca",
    name: "Canxi",
    formula: "Ca",
    desc: "Thành phần quan trọng của xương và răng.",
    recipe: { Ca: 1 },
    type: "Đơn chất",
  },
  {
    id: "mg",
    name: "Magie",
    formula: "Mg",
    desc: "Kim loại nhẹ, dùng trong hợp kim và pháo hoa (cháy sáng).",
    recipe: { Mg: 1 },
    type: "Đơn chất",
  },
  {
    id: "zn",
    name: "Kẽm",
    formula: "Zn",
    desc: "Dùng để mạ (galvanize) sắt thép chống gỉ.",
    recipe: { Zn: 1 },
    type: "Đơn chất",
  },
  {
    id: "pb",
    name: "Chì",
    formula: "Pb",
    desc: "Kim loại nặng, dùng trong ắc quy và che chắn bức xạ.",
    recipe: { Pb: 1 },
    type: "Đơn chất",
  },
  {
    id: "hg",
    name: "Thủy ngân",
    formula: "Hg",
    desc: "Kim loại lỏng ở nhiệt độ phòng, dùng trong nhiệt kế.",
    recipe: { Hg: 1 },
    type: "Đơn chất",
  },

  // --- PHI KIM (Nonmetals) ---
  {
    id: "o2",
    name: "Oxy",
    formula: "O₂",
    desc: "Khí duy trì sự sống, chiếm 21% thể tích không khí.",
    recipe: { O: 2 },
    type: "Đơn chất",
  },
  {
    id: "h2",
    name: "Hydro",
    formula: "H₂",
    desc: "Khí nhẹ nhất, nhiên liệu tiềm năng, thành phần của nước.",
    recipe: { H: 2 },
    type: "Đơn chất",
  },
  {
    id: "n2",
    name: "Nitơ",
    formula: "N₂",
    desc: "Khí trơ, chiếm 78% không khí, dùng trong phân bón và làm lạnh.",
    recipe: { N: 2 },
    type: "Đơn chất",
  },
  {
    id: "c",
    name: "Carbon",
    formula: "C",
    desc: "Cơ sở của mọi sự sống, tồn tại dưới dạng than chì, kim cương.",
    recipe: { C: 1 },
    type: "Đơn chất",
  },
  {
    id: "s",
    name: "Lưu Huỳnh",
    formula: "S",
    desc: "Chất rắn màu vàng, dùng trong sản xuất axit sulfuric và diêm.",
    recipe: { S: 1 },
    type: "Đơn chất",
  },
  {
    id: "p",
    name: "Photpho",
    formula: "P",
    desc: "Quan trọng trong DNA và ATP, dùng làm diêm và phân bón.",
    recipe: { P: 1 },
    type: "Đơn chất",
  },
  {
    id: "cl2",
    name: "Clo",
    formula: "Cl₂",
    desc: "Khí độc màu vàng lục, dùng để tẩy trắng và khử trùng nước.",
    recipe: { Cl: 2 },
    type: "Đơn chất",
  },
  {
    id: "i2",
    name: "Iot",
    formula: "I₂",
    desc: "Chất rắn thăng hoa thành hơi tím, cần thiết cho tuyến giáp.",
    recipe: { I: 2 },
    type: "Đơn chất",
  },

  // --- KHÍ HIẾM (Noble Gases) ---
  {
    id: "he",
    name: "Heli",
    formula: "He",
    desc: "Khí nhẹ thứ hai, dùng để bơm bóng bay và làm lạnh siêu dẫn.",
    recipe: { He: 1 },
    type: "Đơn chất",
  },
  {
    id: "ne",
    name: "Neon",
    formula: "Ne",
    desc: "Khí dùng trong đèn neon tạo ra ánh sáng đỏ-cam đặc trưng.",
    recipe: { Ne: 1 },
    type: "Đơn chất",
  },
  {
    id: "ar",
    name: "Argon",
    formula: "Ar",
    desc: "Khí hiếm phổ biến nhất trong khí quyển, dùng trong bóng đèn.",
    recipe: { Ar: 1 },
    type: "Đơn chất",
  },

  // --- Á KIM (Metalloids) ---
  {
    id: "si",
    name: "Silic",
    formula: "Si",
    desc: "Nguyên tố phổ biến thứ hai trên Trái Đất, dùng làm chất bán dẫn.",
    recipe: { Si: 1 },
    type: "Đơn chất",
  },
  {
    id: "b",
    name: "Bo",
    formula: "B",
    desc: "Dùng trong sản xuất thủy tinh, gốm sứ và chất tẩy rửa.",
    recipe: { B: 1 },
    type: "Đơn chất",
  },
  {
    id: "kr",
    name: "Krypton",
    formula: "Kr",
    desc: "Khí hiếm dùng trong đèn flash tốc độ cao và một số loại đèn chiếu sáng.",
    recipe: { Kr: 1 },
    type: "Đơn chất",
  },
  {
    id: "xe",
    name: "Xenon",
    formula: "Xe",
    desc: "Khí hiếm nặng, dùng trong đèn pha ô tô (HID) và đèn chiếu rạp phim.",
    recipe: { Xe: 1 },
    type: "Đơn chất",
  },
  {
    id: "rn",
    name: "Radon",
    formula: "Rn",
    desc: "Khí hiếm phóng xạ, sản phẩm phân rã của Radi.",
    recipe: { Rn: 1 },
    type: "Đơn chất",
  },

  // --- PHI KIM & HALOGEN (Tiếp theo) ---
  {
    id: "f2",
    name: "Fluor",
    formula: "F₂",
    desc: "Phi kim hoạt động mạnh nhất, dùng trong kem đánh răng (dạng hợp chất) và công nghiệp hạt nhân.",
    recipe: { F: 2 },
    type: "Đơn chất",
  },
  {
    id: "br2",
    name: "Brom",
    formula: "Br₂",
    desc: "Chất lỏng màu nâu đỏ duy nhất là phi kim, dùng trong chất chống cháy và thuốc nhuộm.",
    recipe: { Br: 2 },
    type: "Đơn chất",
  },
  {
    id: "at",
    name: "Astatin",
    formula: "At",
    desc: "Nguyên tố halogen hiếm nhất và phóng xạ.",
    recipe: { At: 1 },
    type: "Đơn chất",
  },
  {
    id: "se",
    name: "Selen",
    formula: "Se",
    desc: "Có đặc tính quang dẫn, dùng trong pin mặt trời và chất nhuộm đỏ thủy tinh.",
    recipe: { Se: 1 },
    type: "Đơn chất",
  },
  {
    id: "te",
    name: "Telur",
    formula: "Te",
    desc: "Đôi khi được coi là á kim, dùng trong hợp kim và chất bán dẫn.",
    recipe: { Te: 1 },
    type: "Đơn chất",
  },

  // --- Á KIM (Tiếp theo) ---
  {
    id: "ge",
    name: "Germani",
    formula: "Ge",
    desc: "Chất bán dẫn quan trọng, dùng trong sợi quang học và thiết bị điện tử.",
    recipe: { Ge: 1 },
    type: "Đơn chất",
  },
  {
    id: "as",
    name: "Asen",
    formula: "As",
    desc: "Á kim độc, dùng trong thuốc trừ sâu và một số hợp kim.",
    recipe: { As: 1 },
    type: "Đơn chất",
  },
  {
    id: "sb",
    name: "Antimon",
    formula: "Sb",
    desc: "Dùng để tăng độ cứng của hợp kim chì và trong chất chống cháy.",
    recipe: { Sb: 1 },
    type: "Đơn chất",
  },

  // --- KIM LOẠI KIỀM & KIỀM THỔ (Tiếp theo) ---
  {
    id: "li",
    name: "Liti",
    formula: "Li",
    desc: "Kim loại nhẹ nhất, quan trọng trong pin sạc (pin Lithium-ion).",
    recipe: { Li: 1 },
    type: "Đơn chất",
  },
  {
    id: "rb",
    name: "Rubidi",
    formula: "Rb",
    desc: "Kim loại kiềm, dùng trong đồng hồ nguyên tử và tế bào quang điện.",
    recipe: { Rb: 1 },
    type: "Đơn chất",
  },
  {
    id: "cs",
    name: "Cesium",
    formula: "Cs",
    desc: "Kim loại kiềm hoạt động mạnh nhất, xác định giây trong đồng hồ nguyên tử.",
    recipe: { Cs: 1 },
    type: "Đơn chất",
  },
  {
    id: "fr",
    name: "Franci",
    formula: "Fr",
    desc: "Kim loại kiềm phóng xạ và cực kỳ hiếm.",
    recipe: { Fr: 1 },
    type: "Đơn chất",
  },
  {
    id: "be",
    name: "Beri",
    formula: "Be",
    desc: "Kim loại nhẹ, cứng, dùng trong hợp kim và cửa sổ tia X.",
    recipe: { Be: 1 },
    type: "Đơn chất",
  },
  {
    id: "sr",
    name: "Stronti",
    formula: "Sr",
    desc: "Kim loại kiềm thổ, dùng trong pháo hoa tạo màu đỏ.",
    recipe: { Sr: 1 },
    type: "Đơn chất",
  },
  {
    id: "ba",
    name: "Bari",
    formula: "Ba",
    desc: "Dùng làm thuốc cản quang X-quang (dạng hợp chất) và trong pháo hoa xanh lục.",
    recipe: { Ba: 1 },
    type: "Đơn chất",
  },
  {
    id: "ra",
    name: "Radi",
    formula: "Ra",
    desc: "Kim loại kiềm thổ phóng xạ, từng được dùng trong sơn phát sáng.",
    recipe: { Ra: 1 },
    type: "Đơn chất",
  },

  // --- KIM LOẠI CHUYỂN TIẾP (Phổ biến) ---
  {
    id: "ti",
    name: "Titan",
    formula: "Ti",
    desc: "Kim loại nhẹ, bền, chống ăn mòn tốt, dùng trong hàng không và cấy ghép y tế.",
    recipe: { Ti: 1 },
    type: "Đơn chất",
  },
  {
    id: "v",
    name: "Vanadi",
    formula: "V",
    desc: "Dùng để tạo ra các hợp kim thép cực kỳ bền và cứng.",
    recipe: { V: 1 },
    type: "Đơn chất",
  },
  {
    id: "cr",
    name: "Crom",
    formula: "Cr",
    desc: "Dùng để mạ (chrome plating) và là thành phần chính của thép không gỉ.",
    recipe: { Cr: 1 },
    type: "Đơn chất",
  },
  {
    id: "mn",
    name: "Mangan",
    formula: "Mn",
    desc: "Quan trọng trong sản xuất thép và trong các enzyme sinh học.",
    recipe: { Mn: 1 },
    type: "Đơn chất",
  },
  {
    id: "ni",
    name: "Niken",
    formula: "Ni",
    desc: "Chống ăn mòn tốt, dùng trong tiền xu và sản xuất thép không gỉ.",
    recipe: { Ni: 1 },
    type: "Đơn chất",
  },
  {
    id: "co",
    name: "Coban",
    formula: "Co",
    desc: "Dùng làm nam châm mạnh và trong các pin sạc hiệu suất cao.",
    recipe: { Co: 1 },
    type: "Đơn chất",
  },
  {
    id: "zr",
    name: "Zirconi",
    formula: "Zr",
    desc: "Chống ăn mòn, dùng trong công nghiệp hạt nhân và đồ trang sức giả kim cương.",
    recipe: { Zr: 1 },
    type: "Đơn chất",
  },
  {
    id: "mo",
    name: "Molypden",
    formula: "Mo",
    desc: "Kim loại có điểm nóng chảy cao, dùng trong hợp kim thép chịu nhiệt.",
    recipe: { Mo: 1 },
    type: "Đơn chất",
  },
  {
    id: "ru",
    name: "Rutheni",
    formula: "Ru",
    desc: "Kim loại nhóm Platin, dùng trong các tiếp điểm điện và chất xúc tác.",
    recipe: { Ru: 1 },
    type: "Đơn chất",
  },
  {
    id: "rh",
    name: "Rhodium",
    formula: "Rh",
    desc: "Kim loại quý hiếm, dùng trong bộ chuyển đổi xúc tác và mạ trang sức.",
    recipe: { Rh: 1 },
    type: "Đơn chất",
  },
  {
    id: "pd",
    name: "Paladi",
    formula: "Pd",
    desc: "Kim loại nhóm Platin, hấp thụ hydro, dùng trong bộ chuyển đổi xúc tác và nha khoa.",
    recipe: { Pd: 1 },
    type: "Đơn chất",
  },
  {
    id: "pt",
    name: "Bạch kim",
    formula: "Pt",
    desc: "Kim loại quý, chống ăn mòn tuyệt vời, dùng trong chất xúc tác và trang sức.",
    recipe: { Pt: 1 },
    type: "Đơn chất",
  },
  {
    id: "ir",
    name: "Iridi",
    formula: "Ir",
    desc: "Kim loại chống ăn mòn nhất, dùng trong đầu bút máy và thiết bị điện tử.",
    recipe: { Ir: 1 },
    type: "Đơn chất",
  },
  {
    id: "os",
    name: "Osmi",
    formula: "Os",
    desc: "Kim loại nặng và đặc nhất, dùng trong các tiếp điểm điện.",
    recipe: { Os: 1 },
    type: "Đơn chất",
  },
  {
    id: "w",
    name: "Wolfram (Tungsten)",
    formula: "W",
    desc: "Kim loại có điểm nóng chảy cao nhất, dùng làm dây tóc bóng đèn.",
    recipe: { W: 1 },
    type: "Đơn chất",
  },
  {
    id: "nb",
    name: "Niobi",
    formula: "Nb",
    desc: "Kim loại siêu dẫn, dùng trong nam châm siêu dẫn.",
    recipe: { Nb: 1 },
    type: "Đơn chất",
  },
  {
    id: "ta",
    name: "Tantan",
    formula: "Ta",
    desc: "Chống ăn mòn, dùng trong tụ điện điện tử và cấy ghép y tế.",
    recipe: { Ta: 1 },
    type: "Đơn chất",
  },

  // --- CÁC KIM LOẠI KHÁC (Post-transition Metals) ---
  {
    id: "ga",
    name: "Gali",
    formula: "Ga",
    desc: "Tan chảy ở nhiệt độ gần nhiệt độ phòng, dùng trong LED (dạng hợp chất GaAs).",
    recipe: { Ga: 1 },
    type: "Đơn chất",
  },
  {
    id: "in",
    name: "Indi",
    formula: "In",
    desc: "Dùng để tạo ra các điện cực trong màn hình phẳng LCD.",
    recipe: { In: 1 },
    type: "Đơn chất",
  },
  {
    id: "tl",
    name: "Tali",
    formula: "Tl",
    desc: "Kim loại mềm, độc, dùng trong thiết bị quang điện tử.",
    recipe: { Tl: 1 },
    type: "Đơn chất",
  },
  {
    id: "sn",
    name: "Thiếc",
    formula: "Sn",
    desc: "Dùng để tráng (tin plating) hộp đựng thực phẩm và làm chất hàn.",
    recipe: { Sn: 1 },
    type: "Đơn chất",
  },
  {
    id: "bi",
    name: "Bismut",
    formula: "Bi",
    desc: "Kim loại nặng không phóng xạ, dùng trong mỹ phẩm và chất hàn không chì.",
    recipe: { Bi: 1 },
    type: "Đơn chất",
  },

  // --- LANTHANIDE (Nguyên tố Đất hiếm) ---
  {
    id: "la",
    name: "Lantan",
    formula: "La",
    desc: "Dùng trong ống kính camera và kính thiên văn chất lượng cao.",
    recipe: { La: 1 },
    type: "Đơn chất",
  },
  {
    id: "ce",
    name: "Ceri",
    formula: "Ce",
    desc: "Dùng để đánh bóng kính và trong bật lửa (hợp kim ferocerium).",
    recipe: { Ce: 1 },
    type: "Đơn chất",
  },
  {
    id: "nd",
    name: "Neodymi",
    formula: "Nd",
    desc: "Tạo ra nam châm vĩnh cửu mạnh nhất thế giới.",
    recipe: { Nd: 1 },
    type: "Đơn chất",
  },
  {
    id: "sm",
    name: "Samari",
    formula: "Sm",
    desc: "Dùng trong nam châm chịu nhiệt độ cao và trong điều trị ung thư.",
    recipe: { Sm: 1 },
    type: "Đơn chất",
  },
  {
    id: "eu",
    name: "Europi",
    formula: "Eu",
    desc: "Dùng để tạo ra ánh sáng đỏ và xanh lam trong màn hình TV màu và đèn huỳnh quang.",
    recipe: { Eu: 1 },
    type: "Đơn chất",
  },
  {
    id: "gd",
    name: "Gadolini",
    formula: "Gd",
    desc: "Dùng làm chất cản quang trong chụp cộng hưởng từ (MRI).",
    recipe: { Gd: 1 },
    type: "Đơn chất",
  },
  {
    id: "tb",
    name: "Terbi",
    formula: "Tb",
    desc: "Tạo ra ánh sáng xanh lục trong màn hình và đèn huỳnh quang.",
    recipe: { Tb: 1 },
    type: "Đơn chất",
  },
  {
    id: "dy",
    name: "Dysprosi",
    formula: "Dy",
    desc: "Dùng trong các nam châm đòi hỏi hoạt động ở nhiệt độ cao.",
    recipe: { Dy: 1 },
    type: "Đơn chất",
  },
  {
    id: "ho",
    name: "Holmi",
    formula: "Ho",
    desc: "Có tính từ mạnh nhất trong các nguyên tố, dùng trong các thiết bị từ trường mạnh.",
    recipe: { Ho: 1 },
    type: "Đơn chất",
  },
  {
    id: "er",
    name: "Erbi",
    formula: "Er",
    desc: "Dùng trong bộ khuếch đại sợi quang và kính hàn.",
    recipe: { Er: 1 },
    type: "Đơn chất",
  },
  {
    id: "tm",
    name: "Tuli",
    formula: "Tm",
    desc: "Dùng trong laser và thiết bị y tế cầm tay.",
    recipe: { Tm: 1 },
    type: "Đơn chất",
  },
  {
    id: "yb",
    name: "Ytterbi",
    formula: "Yb",
    desc: "Dùng trong đồng hồ nguyên tử và laser.",
    recipe: { Yb: 1 },
    type: "Đơn chất",
  },
  {
    id: "lu",
    name: "Luteti",
    formula: "Lu",
    desc: "Nguyên tố cuối cùng của nhóm Lanthanide, dùng trong máy quét PET.",
    recipe: { Lu: 1 },
    type: "Đơn chất",
  },

  // --- ACTINIDE (Phóng xạ) ---
  {
    id: "ac",
    name: "Actini",
    formula: "Ac",
    desc: "Nguyên tố Actini đầu tiên, phóng xạ mạnh.",
    recipe: { Ac: 1 },
    type: "Đơn chất",
  },
  {
    id: "th",
    name: "Thori",
    formula: "Th",
    desc: "Phóng xạ nhẹ, từng dùng làm lưới đèn măng xông.",
    recipe: { Th: 1 },
    type: "Đơn chất",
  },
  {
    id: "pa",
    name: "Protactini",
    formula: "Pa",
    desc: "Nguyên tố Actini hiếm và độc hại.",
    recipe: { Pa: 1 },
    type: "Đơn chất",
  },
  {
    id: "u",
    name: "Urani",
    formula: "U",
    desc: "Nguyên liệu chính cho năng lượng hạt nhân và vũ khí hạt nhân.",
    recipe: { U: 1 },
    type: "Đơn chất",
  },
  {
    id: "np",
    name: "Neptuni",
    formula: "Np",
    desc: "Nguyên tố siêu urani đầu tiên, được tổng hợp nhân tạo.",
    recipe: { Np: 1 },
    type: "Đơn chất",
  },
  {
    id: "pu",
    name: "Plutoni",
    formula: "Pu",
    desc: "Quan trọng cho năng lượng hạt nhân và vũ khí (đồng vị Pu-239).",
    recipe: { Pu: 1 },
    type: "Đơn chất",
  },

  // --- KIM LOẠI CHUYỂN TIẾP (Ít phổ biến hơn) ---
  {
    id: "sc",
    name: "Scandi",
    formula: "Sc",
    desc: "Kim loại chuyển tiếp nhẹ, dùng trong hợp kim nhôm-scandi cho ngành hàng không.",
    recipe: { Sc: 1 },
    type: "Đơn chất",
  },
  {
    id: "y",
    name: "Yttri",
    formula: "Y",
    desc: "Dùng để tạo màu đỏ trong đèn hình CRT (dạng hợp chất) và laser.",
    recipe: { Y: 1 },
    type: "Đơn chất",
  },
  {
    id: "tc",
    name: "Techneti",
    formula: "Tc",
    desc: "Nguyên tố có số nguyên tử nhỏ nhất không có đồng vị ổn định (phóng xạ).",
    recipe: { Tc: 1 },
    type: "Đơn chất",
  },
  {
    id: "hf",
    name: "Hafni",
    formula: "Hf",
    desc: "Chống ăn mòn tốt, dùng trong thanh điều khiển lò phản ứng hạt nhân.",
    recipe: { Hf: 1 },
    type: "Đơn chất",
  },
  {
    id: "re",
    name: "Rheni",
    formula: "Re",
    desc: "Kim loại chịu nhiệt độ cao, dùng trong động cơ phản lực và bộ phận tên lửa.",
    recipe: { Re: 1 },
    type: "Đơn chất",
  },
];
